# Generated by Django 4.2.6 on 2024-03-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymfitness', '0003_enrollment_duedate_enrollment_paymentstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='PaymentStatus',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Price',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='SelectMembershipPlan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='plan',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(max_length=55),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(max_length=25),
        ),
    ]
