# Generated by Django 4.2.6 on 2024-03-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymfitness', '0004_remove_enrollment_duedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='DueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='PaymentStatus',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='Price',
            field=models.IntegerField(blank=True, max_length=55, null=True),
        ),
    ]
