# Generated by Django 4.2.6 on 2024-03-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymfitness', '0006_attendance_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='FullName',
            field=models.CharField(max_length=40),
        ),
    ]
