# Generated by Django 4.2.6 on 2024-04-04 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymfitness', '0010_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='phoneNumber',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
