# Generated by Django 4.2.6 on 2024-04-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymfitness', '0011_attendance_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='phoneNumber',
            field=models.CharField(max_length=10),
        ),
    ]
